{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "85f023a5",
   "metadata": {},
   "source": [
    "# Introduction to Python for Data Science\n",
    "### Tomasz Rodak\n",
    "## Lab VI\n",
    "\n",
    "2024/2025, winter semester\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f3f452f0",
   "metadata": {},
   "source": [
    "## Literature\n",
    "\n",
    "\n",
    "* [The Python Tutorial](https://docs.python.org/3/tutorial/index.html)\n",
    "* [Dive Into Python 3](https://diveintopython3.net/index.html)\n",
    "* [Automate the Boring Stuff with Python](https://automatetheboringstuff.com/)\n",
    "* [Python 3 documentation](https://docs.python.org/3/index.html)\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b95e514a",
   "metadata": {},
   "source": [
    "## Exceptions\n",
    "\n",
    "Errors detected during Python program execution are called *exceptions*. Many standard exceptions are built into Python, they form an inheritance hierarchy. The base class for all built-in exceptions is `BaseException`. The most common exception is `Exception`. From the `Exception` class, many other exception classes are derived, such as:\n",
    "* `ValueError` - when a function receives an argument of the correct type, but with an inappropriate value,\n",
    "* `TypeError` - when a function receives an argument of an inappropriate type,\n",
    "* `NameError` - when a local or global name is not found,\n",
    "* `IndexError` - when a sequence subscript is out of range,\n",
    "* `KeyError` - when a dictionary key is not found,\n",
    "* `ZeroDivisionError` - when division or modulo by zero is attempted,\n",
    "* `FileNotFoundError` - when a file or directory is requested but doesn't exist,\n",
    "\n",
    "and many others. The hierarchy of exceptions is presented [here](https://docs.python.org/3/library/exceptions.html#exception-hierarchy).\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "964db85b",
   "metadata": {},
   "source": [
    "### Exercise 6.1\n",
    "\n",
    "Write program examples that raises the mentioned above exceptions.\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "04ee4ea3",
   "metadata": {},
   "source": [
    "## Handling exceptions\n",
    "\n",
    "Exceptions can be handled using the `try` statement. The most basic form of the `try` statement is:\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except <exception>:\n",
    "    # code that handles the exception\n",
    "```\n",
    "\n",
    "The `try` statement works as follows:\n",
    "\n",
    "1. The code block within the `try` statement is executed.\n",
    "2. If no exception occurs, the `except` block is skipped and the `try` statement is finished.\n",
    "3. If an exception occurs during the execution of the `try` block, the rest of the block is skipped. Then, if the exception type matches the exception named after the `except` keyword, the code block following the `except` keyword is executed. If the exception type does not match, it is passed to higher level of the stack. If no handler is found, the exception is an *unhandled exception* and the program stops with an error message.\n",
    "\n",
    "### Exercise 6.2\n",
    "\n",
    "Write a program `square,py` that reads a floating-point number from the user and prints its square. If the user enters a string that cannot be converted to a number, the program should print an error message.\n",
    "\n",
    "Example:\n",
    "\n",
    "```\n",
    ">>> %Run square.py\n",
    "Enter a number: 5\n",
    "25.0\n",
    ">>> %Run square.py\n",
    "Enter a number: -3.5\n",
    "12.25\n",
    ">>> %Run square.py\n",
    "Enter a number: abc\n",
    "Error: invalid input\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4535afbe",
   "metadata": {},
   "source": [
    "### Exercise 6.3\n",
    "\n",
    "Write a program `quotient.py` that reads two integers from the user and calculates their quotient. The program should handle two types of exceptions:\n",
    "\n",
    "* `ValueError`: if the user enters a string instead of an integer,\n",
    "* `ZeroDivisionError`: if the user enters 0 as the divisor.\n",
    "\n",
    "The program should display an error message appropriate to the type of exception that was raised.\n",
    "\n",
    "Example:\n",
    "\n",
    "```\n",
    ">>> %Run quotient.py\n",
    "Enter the dividend: 10\n",
    "Enter the divisor: 2\n",
    "The quotient is 5\n",
    ">>> %Run quotient.py\n",
    "Enter the dividend: 10\n",
    "Enter the divisor: 0\n",
    "Error: division by zero\n",
    ">>> %Run quotient.py\n",
    "Enter the dividend: abc\n",
    "Enter the divisor: 2\n",
    "Error: invalid input\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "f237bae7",
   "metadata": {},
   "source": [
    "### Exercise 6.4\n",
    "\n",
    "Write a program `average.py`. The program reads a sequence of integers separated by spaces or tabs from the user. The program should display the sum and the arithmetic mean of the sequence. The program should enforce the correct format of the input data: after entering incorrect data, the program should request the data again.\n",
    "\n",
    "Use the `try` statement. Process the string with the `split()` method and the `int()` function.\n",
    "\n",
    "Example:\n",
    "\n",
    "```\n",
    ">>> %Run average.py\n",
    "Numbers: 4 3 2 1 5\n",
    "Sum: 15\n",
    "Average: 3.0\n",
    ">>> %Run average.py\n",
    "Numbers: 4 3 2 1 abc 5\n",
    "Error: invalid input\n",
    "Numbers: 4 3 2 1 5\n",
    "Sum: 15\n",
    "Average: 3.0\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0f369dfb",
   "metadata": {},
   "source": [
    "<!-- Zmień program z punktu II.2 tak, aby dawał użytkownikowi trzy szanse na wprowadzenie prawidłowych danych -- później program kończy działanie stosownym komunikatem. -->\n",
    "\n",
    "### Exercise 6.5\n",
    "\n",
    "Write a program `average2.py` which is a modification of the program from the previous exercise. The program should give the user three chances to enter the correct data. If the user does not enter the correct data after three attempts, the program should display an error message and end.\n",
    "\n",
    "Example:\n",
    "\n",
    "```\n",
    ">>> %Run average2.py\n",
    "Numbers: 4 3 2 1 abc 5\n",
    "Error: invalid input\n",
    "Numbers: 4 3 2 1 abc 5\n",
    "Error: invalid input\n",
    "Numbers: 4 3 2 1 abc 5\n",
    "Error: invalid input\n",
    "You have exceeded the number of attempts\n",
    ">>> %Run average2.py\n",
    "Numbers: 4 3 2 1 5\n",
    "Sum: 15\n",
    "Average: 3.0\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "357696cd",
   "metadata": {},
   "source": [
    "## Detailes of `try` statement\n",
    "\n",
    "The `try` is followed by `except`, `else`, and `finally` blocks in many different combinations, but at least one of `except` or `finally` must be present. The `else` block is executed if the code block in the `try` statement does not raise an exception. The `finally` block is executed after the `try` block, regardless of whether an exception was raised or not.\n",
    "\n",
    "```python\n",
    "try:\n",
    "    # code that may raise an exception\n",
    "except <exception>:\n",
    "    # code that handles the exception\n",
    "else:\n",
    "    # code that is executed if no exception was raised\n",
    "finally:\n",
    "    # code that is always executed\n",
    "```\n",
    "\n",
    "### `else` block\n",
    "\n",
    "The `else` block is executed if the code block in the `try` statement does not raise an exception and is executed before the `finally` block (if present). If an exception is raised, the `else` block is skipped. The `else` block is useful for code that should run only if no exceptions were raised. \n",
    "\n",
    "### `finally` block\n",
    "\n",
    "The `finally` block is executed after the `try` block, regardless of whether an exception was raised or not. The `finally` block is useful for cleaning up resources, such as closing files or releasing network connections."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "74717961",
   "metadata": {},
   "source": [
    "## How to open a file safely\n",
    "\n",
    "When opening a file, after processing it, it **always** should be closed. However, an exception raised earlier in the code block can prevent the `close()` method from being executed, even if it's included. To ensure that the file is properly closed, we can use the `finally` block:\n",
    "\n",
    "```python\n",
    "f = open(<path to the file>, ...)\n",
    "try:\n",
    "    # code that processes the file\n",
    "finally:\n",
    "    f.close()\n",
    "```\n",
    "\n",
    "### Exercise 6.6\n",
    "\n",
    "Write a program `file_size.py` that reads the name of a file from the user and displays its size in bytes. If the file does not exist or cannot be opened, the program should display a suitable error message. To compute the size of the file:\n",
    "* open the file in binary mode,\n",
    "* use the `read()` method (it reads the entire file into a byte string),\n",
    "* use the `len()` function.\n",
    "\n",
    "Example:\n",
    "\n",
    "```\n",
    ">>> %Run file_size.py\n",
    "Enter the file name: file_size.py\n",
    "The size of the file is 1234 bytes\n",
    ">>> %Run file_size.py\n",
    "Enter the file name: KFLQFWLQMKWFLQMFQW.txt\n",
    "Error: file not found\n",
    ">>> %Run file_size.py\n",
    "Enter the file name: /etc/passwd\n",
    "Error: destination exists but cannot be opened\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9c1aaef",
   "metadata": {},
   "source": [
    "The pattern of opening a file (or another resource) and closing it safely is so common that Python provides a special syntax for it: the `with` statement. The `with` statement is a compound statement that ensures that a resource is properly cleaned up after its use. It has the following syntax:\n",
    "\n",
    "```python\n",
    "with <expression> as <variable>:\n",
    "    # code that uses the resource\n",
    "```\n",
    "\n",
    "The `expression` must return an object that supports the context manager protocol (`open()` function returns such an object). The `variable` is assigned the object returned by the `expression`. The `with` statement ensures that the `__enter__()` method of the object is called before the block is executed and the `__exit__()` method is called after the block is executed. The `__exit__()` method is called even if an exception is raised in the block.\n",
    "\n",
    "So the proper pythonic way to open a file looks like this:\n",
    "\n",
    "```python\n",
    "with open(<path to the file>, ...) as f:\n",
    "    # code that processes the file\n",
    "    # no need to call f.close()\n",
    "```\n",
    "\n",
    "The `open()` function returns a file object. The `as` keyword is used to assign the file object to a variable. The file is automatically closed when the block is exited, even if exceptions are raised. \n",
    "\n",
    "### Exercise 6.7\n",
    "\n",
    "Rewrite the program from the previous exercise using the `with` statement.\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4ab9af60",
   "metadata": {},
   "source": [
    "\n",
    "## Raising exceptions\n",
    "\n",
    "Exceptions can be raised using the `raise` statement:\n",
    "\n",
    "```python\n",
    ">>> raise <exception>\n",
    "```\n",
    "\n",
    "where `<exception>` is an exception class or an instance of an exception class. The `raise` statement can be used without an argument to re-raise the last exception.\n",
    "\n",
    "When raising an exception, you can provide an error message:\n",
    "\n",
    "```python\n",
    ">>> raise ValueError('Invalid value')\n",
    "Traceback (most recent call last):\n",
    "    File \"<stdin>\", line 1, in <module>\n",
    "ValueError: Invalid value\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1a8748fc",
   "metadata": {},
   "source": [
    "## `assert` statement\n",
    "\n",
    "The `assert` statement is used to check the correctness of the program. It has the following form:\n",
    "\n",
    "```python\n",
    "assert <condition>, <message>\n",
    "```\n",
    "\n",
    "If the condition is `False`, the `AssertionError` exception is raised with the message provided. Otherwise, the program continues to execute normally."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e32532d",
   "metadata": {},
   "source": [
    "## Unit tests\n",
    "\n",
    "Now we know how to handle exceptions hence we can introduce the concept of unit tests. A unit test is a piece of code that tests a small part of the program, typically a function, class method, or a class. The goal of unit testing is to verify that the code works as expected. There are many libraries for writing unit tests in Python, such as `unittest` or `pytest`, but now we will try to write simple tests using the `assert` and `try` statements.\n",
    "\n",
    "### Exercise 6.8\n",
    "\n",
    "The code below provides a unit tests for the module `mean.py`. Copy the code to the file `test_mean.py` then write the module `mean.py` and put it in the same directory as the test file. Check carefully the code of the tests and write the module `mean.py` according to them. Run the tests.\n",
    "\n",
    "```python\n",
    "# test_mean.py\n",
    "import math\n",
    "\n",
    "from mean import arithmetic_mean, geometric_mean, mean\n",
    "\n",
    "def test_arithmetic_mean():\n",
    "    assert arithmetic_mean([7]) == 7\n",
    "    assert arithmetic_mean([2.34, -2.34]) == 0\n",
    "    assert math.isclose(arithmetic_mean([1, 2, 3, 4, 5]), 3.0)\n",
    "\n",
    "\n",
    "def test_arithmetic_mean_empty():\n",
    "    try:\n",
    "        arithmetic_mean([])\n",
    "    except ValueError as e:\n",
    "        assert str(e) == \"The sequence is empty\", \"Error message is incorrect\"\n",
    "    except Exception as e:\n",
    "        raise AssertionError(\"The sequence is empty, but the exception is incorrect\")\n",
    "    else:\n",
    "        raise AssertionError(\"The sequence is empty, but no exception was raised\")\n",
    "\n",
    "\n",
    "def test_geometric_mean():\n",
    "    # 5-th root of 1 is 1\n",
    "    assert geometric_mean([1, 1, 1, 1, 1]) == 1\n",
    "    # 5-th root of 2**5 is 2\n",
    "    assert math.isclose(geometric_mean([2, 2, 2, 2, 2]), 2.0)\n",
    "\n",
    "\n",
    "def test_geometric_mean_empty():\n",
    "    try:\n",
    "        geometric_mean([])\n",
    "    except ValueError as e:\n",
    "        assert str(e) == \"The sequence is empty\", \"Error message is incorrect\"\n",
    "    except Exception as e:\n",
    "        raise AssertionError(\"The sequence is empty, but the exception is incorrect\")\n",
    "    else:\n",
    "        raise AssertionError(\"The sequence is empty, but no exception was raised\")\n",
    "\n",
    "\n",
    "def test_mean():\n",
    "    assert mean([1, 2, 3, 4, 5], \"arithmetic\") == 3.0\n",
    "    assert math.isclose(\n",
    "        mean([1, 2, 3, 4, 5], \"geometric\"), (1 * 2 * 3 * 4 * 5) ** (1 / 5)\n",
    "    )\n",
    "\n",
    "\n",
    "def test_mean_empty():\n",
    "    try:\n",
    "        mean([], \"arithmetic\")\n",
    "    except ValueError as e:\n",
    "        assert str(e) == \"The sequence is empty\", \"Error message is incorrect\"\n",
    "    except Exception as e:\n",
    "        raise AssertionError(\"The sequence is empty, but the exception is incorrect\")\n",
    "    else:\n",
    "        raise AssertionError(\"The sequence is empty, but no exception was raised\")\n",
    "\n",
    "    try:\n",
    "        mean([], \"geometric\")\n",
    "    except ValueError as e:\n",
    "        assert str(e) == \"The sequence is empty\", \"Error message is incorrect\"\n",
    "    except Exception as e:\n",
    "        raise AssertionError(\"The sequence is empty, but the exception is incorrect\")\n",
    "    else:\n",
    "        raise AssertionError(\"The sequence is empty, but no exception was raised\")\n",
    "\n",
    "\n",
    "def test_mean_incorrect_type():\n",
    "    try:\n",
    "        mean([1, 2, 3, 4, 5], \"abc\")\n",
    "    except ValueError as e:\n",
    "        assert str(e) == \"Incorrect type of mean\", \"Error message is incorrect\"\n",
    "    except Exception as e:\n",
    "        raise AssertionError(\"Incorrect type of mean, but the exception is incorrect\")\n",
    "    else:\n",
    "        raise AssertionError(\"Incorrect type of mean, but no exception was raised\")\n",
    "\n",
    "\n",
    "def test_mean_default_type():\n",
    "    try:\n",
    "        x = mean([1, 2, 3, 4, 5])\n",
    "    except Exception as e:\n",
    "        raise AssertionError(\n",
    "            \"The default type of mean is arithmetic, but an exception was raised\"\n",
    "        )\n",
    "    else:\n",
    "        assert math.isclose(x, 3.0)\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    test_arithmetic_mean()\n",
    "    test_arithmetic_mean_empty()\n",
    "    test_geometric_mean()\n",
    "    test_geometric_mean_empty()\n",
    "    test_mean()\n",
    "    test_mean_empty()\n",
    "    test_mean_incorrect_type()\n",
    "    test_mean_default_type()\n",
    "    print(\"All tests passed\")\n",
    "```\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "af4ffe7a",
   "metadata": {},
   "source": [
    "Writing tests is a good practice and very common in software development. [Here](https://github.com/rodakt/ItP/blob/main/tests/lab_6/test_mean.py) you can find the same tests as above but written in the `unittest` framework. You can run them by executing the command:\n",
    "\n",
    "```bash\n",
    "$ python test_mean.py\n",
    "```\n",
    "\n",
    "Ensure that the file `mean.py` is in the same directory as the test file.\n",
    "\n",
    "### Exercise 6.9\n",
    "\n",
    "Test your `mean.py` module against the mentioned above tests.\n",
    "\n",
    "---"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "py312",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
